export const PATHNAME = {
    SCREENDASHBOARD: '/home',
    // SCREENLOGIN: '/login',
    SCREENLOGIN: '/',
    SCREENORDERCOUNTERS: '/order-counters',
    SCREENORDERUSER: '/order-onlines',
    SCREENPROMMOTIONS: '/prommotions',
    SCREENSTAFF: '/accounts/staffs',
    SCREENUSER: '/accounts/users',
    SCREENINFOUSER: '/info-user',
    SCREENSALESCOUNTER: '/sales-counter',
    SCREENWORK: '/works',
    SCREENROLE: '/roles',
    SCREENDECENTRALIZATION: '/role-decentralization',
    SCREENDCREATEROLE: '/role-create',
    SCREENSETTINGS: '/settings',
    SCREENSETTINGCHAT: '/settings/chat',
    SCREENSETTINGNOTIFI: '/settings/notifi',
    SCREENSETTINGSTORE: '/settings/store',
    SCREENSETTINGPRINT: '/settings/print',
    SCREENSETTINGLANGUAGE: '/settings/language',
    SCREENSETTINGBANNERS: '/bc/banners',
    SCREENSETTINGCATEGORIES: '/bc/categories',
    SCREENSETTINGPRODUCTS: '/sp/products',
    SCREENSETTINGPROMMOTIONS: '/sp/prommotions',
    SCREENERROR: '/error-404',
}